

DROP TABLE IF EXISTS `PhoneCode`;

CREATE TABLE `PhoneCode` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `bindphone` VARCHAR(30) NOT NULL,
  `code` CHAR(4) NOT NULL,
  `exptime` DATETIME DEFAULT '1900-01-01 00:00:00',
  PRIMARY KEY (`f_id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

